# Generated by Django 3.0.5 on 2020-04-01 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('open', models.BooleanField(default=False)),
                ('full', models.BooleanField(default=False)),
                ('holder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('inside', models.BooleanField(default=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zettelbox.Box')),
            ],
        ),
    ]
