# Generated by Django 3.0.5 on 2020-04-04 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zettelbox', '0004_paper_holder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='inside',
        ),
    ]
