# Generated by Django 3.0.5 on 2020-04-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettelbox', '0006_paper_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='paper',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
